[package]
name = "random_number_generators"
version = "0.1.0"
authors = ["Malcolm Ramsay <malramsay64@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "~0.8.0"
rand_core = "~0.5"
rand = "~0.6"
rand_pcg = "~0.2.0"
rand_xorshift = "~0.2.0"
rand_xoshiro = "~0.2.0"
clap = "~2.33"
sfmt = "~0.5.0"
